name: "Deploy to NPM"

on:
  push:
    branches: [ "master", "release/*" ]
    tags: ["v[0-9]+*"]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  IS_RELEASE: ${{ github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v') }}

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      # -----------------------
      - name: Clone oll-visual-tester repository
        uses: actions/checkout@v4
        with:
          path: oll-visual-tester

      # Install NodeJS
      # --------------
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: oll-visual-tester/npm-shrinkwrap.json

      # Install NPM modules
      # -------------------
      - name: Install NPM modules
        shell: bash
        run: |
          cd oll-visual-tester
          sudo apt-get install -y libvips
          npm ci --ignore-scripts --loglevel error
          npx playwright install --with-deps

      # Run tests and build
      # -------------------
      - name: Run tests
        shell: bash
        run: |
          cd oll-visual-tester
          npm test

  release-to-npm:
    runs-on: ubuntu-latest
    needs: install-and-test
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
